services:
  traefik:
    container_name: traefik
    image: traefik:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - /opt/appdata/traefik/:/etc/traefik/
    networks:
      - declaredockernetwork
    environment:
      CF_DNS_API_TOKEN: ${CF_DNS_API_TOKEN}
    restart: always
    security_opt:
      - no-new-privileges:true
networks:
  declaredockernetwork:
    external: true
